### ISSUE TITLE
Swig dependencies

### ISSUE THREAD

**Issue by ulas-atila** [RasterBurn/grunt-swig-compile#6]
Hi

I use grunt and in one of my project i need this task. But in your package.json, swig is in devDependencies and not dependencies and i don't have swig in my defaults package so your task don't work on my setting.

Can you move swig in package.json under dependencies categories?

Thanks you and sorry for my bad english.

**Comment by RasterBurn** [comment]
It's not a good idea to specify swig in the dependencies section because I don't want to prescribe any specific version of swig.  The project which depends on this plugin should specify the version of swig to use, not the grunt plugin.

The reason swig is in the devDependencies is because it is needed for unit tests.

I suppose [peerDependencies](http://blog.nodejs.org/2013/02/07/peer-dependencies/) could be used, but I don't really want to take on figuring out what range of swig versions to specify, and keeping that constantly up-to-date.
